unstable_features = true
struct_field_align_threshold = 80
fn_params_layout = "Vertical"
struct_lit_single_line = false
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
use_field_init_shorthand = true
wrap_comments = true
comment_width = 60